# Generated by Django 5.2.5 on 2025-09-06 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="name",
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="working_hours",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Time must be in format: 09:00 AM - 08:00 PM",
                        regex="^(0?[1-9]|1[0-2]):[0-5][0-9]\\s?(AM|PM)\\s*-\\s*(0?[1-9]|1[0-2]):[0-5][0-9]\\s?(AM|PM)$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="slot_range",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Time must be in format: 09:00 AM - 08:00 PM",
                        regex="^(0?[1-9]|1[0-2]):[0-5][0-9]\\s?(AM|PM)\\s*-\\s*(0?[1-9]|1[0-2]):[0-5][0-9]\\s?(AM|PM)$",
                    )
                ],
            ),
        ),
    ]
