# Generated by Django 5.2.5 on 2025-09-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_remove_staff_name_alter_organization_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="disabled_since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
