# Generated by Django 5.2.5 on 2025-09-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_organization_disabled_since_organization_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="disabled_since",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="is_active",
        ),
    ]
