# Generated by Django 5.2.5 on 2025-09-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_timeslot_is_active_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="disabled_since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
