# Generated by Django 5.2.5 on 2025-09-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_organization_disabled_since_organization_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="is_active",
        ),
    ]
