# Generated by Django 5.2.5 on 2025-09-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_remove_organization_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
